language: python

jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS

before_install:
  - pip3 install pytest parameterized matplotlib loris ipdb

install:
  - python3 setup.py install

script:
  - python3 -m pytest --capture=no
